//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 10:47:10 AM CET 
//


package fr.emn.examination.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="information">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="enTete">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="objet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="auteur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="destination" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="UV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="coefficient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="commentaires" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preambule" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="introduction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enonce">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="exercice">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="introduction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="question" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="consigne" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;choice>
 *                                         &lt;element name="codeOuTexte">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="segment" maxOccurs="unbounded">
 *                                                     &lt;complexType>
 *                                                       &lt;complexContent>
 *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                           &lt;sequence>
 *                                                             &lt;element name="typeCorrection">
 *                                                               &lt;simpleType>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                   &lt;enumeration value="syntaxeSeulement"/>
 *                                                                   &lt;enumeration value="testCompilationPuisExecution"/>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/simpleType>
 *                                                             &lt;/element>
 *                                                             &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                                           &lt;/sequence>
 *                                                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                         &lt;/restriction>
 *                                                       &lt;/complexContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                         &lt;element name="caseacocher">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="case" maxOccurs="unbounded">
 *                                                     &lt;complexType>
 *                                                       &lt;simpleContent>
 *                                                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                                           &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                                         &lt;/extension>
 *                                                       &lt;/simpleContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                         &lt;element name="choixMultiples">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="choix" maxOccurs="unbounded" minOccurs="2">
 *                                                     &lt;complexType>
 *                                                       &lt;simpleContent>
 *                                                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                                         &lt;/extension>
 *                                                       &lt;/simpleContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                   &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/choice>
 *                                       &lt;element name="protocole">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="nbEssais" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *                                               &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="duree" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="nbPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                                     &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                           &lt;attribute name="langage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="coefficient" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="conclusion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "information",
    "preambule",
    "introduction",
    "enonce",
    "conclusion"
})
@XmlRootElement(name = "examen")
public class Examen {

    @XmlElement(required = true)
    protected Examen.Information information;
    protected String preambule;
    protected String introduction;
    @XmlElement(required = true)
    protected Examen.Enonce enonce;
    protected String conclusion;

    /**
     * Gets the value of the information property.
     * 
     * @return
     *     possible object is
     *     {@link Examen.Information }
     *     
     */
    public Examen.Information getInformation() {
        return information;
    }

    /**
     * Sets the value of the information property.
     * 
     * @param value
     *     allowed object is
     *     {@link Examen.Information }
     *     
     */
    public void setInformation(Examen.Information value) {
        this.information = value;
    }

    /**
     * Gets the value of the preambule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreambule() {
        return preambule;
    }

    /**
     * Sets the value of the preambule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreambule(String value) {
        this.preambule = value;
    }

    /**
     * Gets the value of the introduction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * Sets the value of the introduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntroduction(String value) {
        this.introduction = value;
    }

    /**
     * Gets the value of the enonce property.
     * 
     * @return
     *     possible object is
     *     {@link Examen.Enonce }
     *     
     */
    public Examen.Enonce getEnonce() {
        return enonce;
    }

    /**
     * Sets the value of the enonce property.
     * 
     * @param value
     *     allowed object is
     *     {@link Examen.Enonce }
     *     
     */
    public void setEnonce(Examen.Enonce value) {
        this.enonce = value;
    }

    /**
     * Gets the value of the conclusion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConclusion() {
        return conclusion;
    }

    /**
     * Sets the value of the conclusion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConclusion(String value) {
        this.conclusion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="exercice">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="introduction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="question" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="consigne" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;choice>
     *                               &lt;element name="codeOuTexte">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="segment" maxOccurs="unbounded">
     *                                           &lt;complexType>
     *                                             &lt;complexContent>
     *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                 &lt;sequence>
     *                                                   &lt;element name="typeCorrection">
     *                                                     &lt;simpleType>
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                                         &lt;enumeration value="syntaxeSeulement"/>
     *                                                         &lt;enumeration value="testCompilationPuisExecution"/>
     *                                                       &lt;/restriction>
     *                                                     &lt;/simpleType>
     *                                                   &lt;/element>
     *                                                   &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                                                 &lt;/sequence>
     *                                                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                               &lt;/restriction>
     *                                             &lt;/complexContent>
     *                                           &lt;/complexType>
     *                                         &lt;/element>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element name="caseacocher">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="case" maxOccurs="unbounded">
     *                                           &lt;complexType>
     *                                             &lt;simpleContent>
     *                                               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                                                 &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                                               &lt;/extension>
     *                                             &lt;/simpleContent>
     *                                           &lt;/complexType>
     *                                         &lt;/element>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element name="choixMultiples">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="choix" maxOccurs="unbounded" minOccurs="2">
     *                                           &lt;complexType>
     *                                             &lt;simpleContent>
     *                                               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                                               &lt;/extension>
     *                                             &lt;/simpleContent>
     *                                           &lt;/complexType>
     *                                         &lt;/element>
     *                                         &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                             &lt;/choice>
     *                             &lt;element name="protocole">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="nbEssais" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
     *                                     &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="duree" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="nbPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *                 &lt;attribute name="langage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="coefficient" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exercice"
    })
    public static class Enonce {

        @XmlElement(required = true)
        protected Examen.Enonce.Exercice exercice;

        /**
         * Gets the value of the exercice property.
         * 
         * @return
         *     possible object is
         *     {@link Examen.Enonce.Exercice }
         *     
         */
        public Examen.Enonce.Exercice getExercice() {
            return exercice;
        }

        /**
         * Sets the value of the exercice property.
         * 
         * @param value
         *     allowed object is
         *     {@link Examen.Enonce.Exercice }
         *     
         */
        public void setExercice(Examen.Enonce.Exercice value) {
            this.exercice = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="introduction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="question" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="consigne" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;choice>
         *                     &lt;element name="codeOuTexte">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element name="segment" maxOccurs="unbounded">
         *                                 &lt;complexType>
         *                                   &lt;complexContent>
         *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                       &lt;sequence>
         *                                         &lt;element name="typeCorrection">
         *                                           &lt;simpleType>
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                               &lt;enumeration value="syntaxeSeulement"/>
         *                                               &lt;enumeration value="testCompilationPuisExecution"/>
         *                                             &lt;/restriction>
         *                                           &lt;/simpleType>
         *                                         &lt;/element>
         *                                         &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                                       &lt;/sequence>
         *                                       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                                     &lt;/restriction>
         *                                   &lt;/complexContent>
         *                                 &lt;/complexType>
         *                               &lt;/element>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                     &lt;element name="caseacocher">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element name="case" maxOccurs="unbounded">
         *                                 &lt;complexType>
         *                                   &lt;simpleContent>
         *                                     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *                                       &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                                     &lt;/extension>
         *                                   &lt;/simpleContent>
         *                                 &lt;/complexType>
         *                               &lt;/element>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                     &lt;element name="choixMultiples">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element name="choix" maxOccurs="unbounded" minOccurs="2">
         *                                 &lt;complexType>
         *                                   &lt;simpleContent>
         *                                     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                                       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *                                     &lt;/extension>
         *                                   &lt;/simpleContent>
         *                                 &lt;/complexType>
         *                               &lt;/element>
         *                               &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                   &lt;/choice>
         *                   &lt;element name="protocole">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="nbEssais" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
         *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="duree" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="nbPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *       &lt;attribute name="langage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="coefficient" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "introduction",
            "question"
        })
        public static class Exercice {

            protected String introduction;
            @XmlElement(required = true)
            protected List<Examen.Enonce.Exercice.Question> question;
            @XmlAttribute
            protected String title;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger id;
            @XmlAttribute(required = true)
            protected String langage;
            @XmlAttribute
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger coefficient;

            /**
             * Gets the value of the introduction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIntroduction() {
                return introduction;
            }

            /**
             * Sets the value of the introduction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIntroduction(String value) {
                this.introduction = value;
            }

            /**
             * Gets the value of the question property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the question property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getQuestion().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Examen.Enonce.Exercice.Question }
             * 
             * 
             */
            public List<Examen.Enonce.Exercice.Question> getQuestion() {
                if (question == null) {
                    question = new ArrayList<Examen.Enonce.Exercice.Question>();
                }
                return this.question;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setId(BigInteger value) {
                this.id = value;
            }

            /**
             * Gets the value of the langage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLangage() {
                return langage;
            }

            /**
             * Sets the value of the langage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLangage(String value) {
                this.langage = value;
            }

            /**
             * Gets the value of the coefficient property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCoefficient() {
                return coefficient;
            }

            /**
             * Sets the value of the coefficient property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCoefficient(BigInteger value) {
                this.coefficient = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="consigne" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;choice>
             *           &lt;element name="codeOuTexte">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="segment" maxOccurs="unbounded">
             *                       &lt;complexType>
             *                         &lt;complexContent>
             *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                             &lt;sequence>
             *                               &lt;element name="typeCorrection">
             *                                 &lt;simpleType>
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                                     &lt;enumeration value="syntaxeSeulement"/>
             *                                     &lt;enumeration value="testCompilationPuisExecution"/>
             *                                   &lt;/restriction>
             *                                 &lt;/simpleType>
             *                               &lt;/element>
             *                               &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *                             &lt;/sequence>
             *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                           &lt;/restriction>
             *                         &lt;/complexContent>
             *                       &lt;/complexType>
             *                     &lt;/element>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *           &lt;element name="caseacocher">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="case" maxOccurs="unbounded">
             *                       &lt;complexType>
             *                         &lt;simpleContent>
             *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *                             &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *                           &lt;/extension>
             *                         &lt;/simpleContent>
             *                       &lt;/complexType>
             *                     &lt;/element>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *           &lt;element name="choixMultiples">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="choix" maxOccurs="unbounded" minOccurs="2">
             *                       &lt;complexType>
             *                         &lt;simpleContent>
             *                           &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *                           &lt;/extension>
             *                         &lt;/simpleContent>
             *                       &lt;/complexType>
             *                     &lt;/element>
             *                     &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *         &lt;/choice>
             *         &lt;element name="protocole">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="nbEssais" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
             *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="duree" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="nbPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
             *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "consigne",
                "codeOuTexte",
                "caseacocher",
                "choixMultiples",
                "protocole"
            })
            public static class Question {

                @XmlElement(required = true)
                protected String consigne;
                protected Examen.Enonce.Exercice.Question.CodeOuTexte codeOuTexte;
                protected Examen.Enonce.Exercice.Question.Caseacocher caseacocher;
                protected Examen.Enonce.Exercice.Question.ChoixMultiples choixMultiples;
                @XmlElement(required = true)
                protected Examen.Enonce.Exercice.Question.Protocole protocole;
                @XmlAttribute(required = true)
                @XmlSchemaType(name = "positiveInteger")
                protected BigInteger id;
                @XmlAttribute
                protected String title;

                /**
                 * Gets the value of the consigne property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConsigne() {
                    return consigne;
                }

                /**
                 * Sets the value of the consigne property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConsigne(String value) {
                    this.consigne = value;
                }

                /**
                 * Gets the value of the codeOuTexte property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Examen.Enonce.Exercice.Question.CodeOuTexte }
                 *     
                 */
                public Examen.Enonce.Exercice.Question.CodeOuTexte getCodeOuTexte() {
                    return codeOuTexte;
                }

                /**
                 * Sets the value of the codeOuTexte property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Examen.Enonce.Exercice.Question.CodeOuTexte }
                 *     
                 */
                public void setCodeOuTexte(Examen.Enonce.Exercice.Question.CodeOuTexte value) {
                    this.codeOuTexte = value;
                }

                /**
                 * Gets the value of the caseacocher property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Examen.Enonce.Exercice.Question.Caseacocher }
                 *     
                 */
                public Examen.Enonce.Exercice.Question.Caseacocher getCaseacocher() {
                    return caseacocher;
                }

                /**
                 * Sets the value of the caseacocher property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Examen.Enonce.Exercice.Question.Caseacocher }
                 *     
                 */
                public void setCaseacocher(Examen.Enonce.Exercice.Question.Caseacocher value) {
                    this.caseacocher = value;
                }

                /**
                 * Gets the value of the choixMultiples property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Examen.Enonce.Exercice.Question.ChoixMultiples }
                 *     
                 */
                public Examen.Enonce.Exercice.Question.ChoixMultiples getChoixMultiples() {
                    return choixMultiples;
                }

                /**
                 * Sets the value of the choixMultiples property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Examen.Enonce.Exercice.Question.ChoixMultiples }
                 *     
                 */
                public void setChoixMultiples(Examen.Enonce.Exercice.Question.ChoixMultiples value) {
                    this.choixMultiples = value;
                }

                /**
                 * Gets the value of the protocole property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Examen.Enonce.Exercice.Question.Protocole }
                 *     
                 */
                public Examen.Enonce.Exercice.Question.Protocole getProtocole() {
                    return protocole;
                }

                /**
                 * Sets the value of the protocole property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Examen.Enonce.Exercice.Question.Protocole }
                 *     
                 */
                public void setProtocole(Examen.Enonce.Exercice.Question.Protocole value) {
                    this.protocole = value;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setId(BigInteger value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the title property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTitle() {
                    return title;
                }

                /**
                 * Sets the value of the title property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTitle(String value) {
                    this.title = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="case" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
                 *                 &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "_case"
                })
                public static class Caseacocher {

                    @XmlElement(name = "case", required = true)
                    protected List<Examen.Enonce.Exercice.Question.Caseacocher.Case> _case;

                    /**
                     * Gets the value of the case property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the case property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getCase().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Examen.Enonce.Exercice.Question.Caseacocher.Case }
                     * 
                     * 
                     */
                    public List<Examen.Enonce.Exercice.Question.Caseacocher.Case> getCase() {
                        if (_case == null) {
                            _case = new ArrayList<Examen.Enonce.Exercice.Question.Caseacocher.Case>();
                        }
                        return this._case;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
                     *       &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Case {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(required = true)
                        @XmlSchemaType(name = "positiveInteger")
                        protected BigInteger id;
                        @XmlAttribute(required = true)
                        protected boolean correction;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the id property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigInteger }
                         *     
                         */
                        public BigInteger getId() {
                            return id;
                        }

                        /**
                         * Sets the value of the id property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigInteger }
                         *     
                         */
                        public void setId(BigInteger value) {
                            this.id = value;
                        }

                        /**
                         * Gets the value of the correction property.
                         * 
                         */
                        public boolean isCorrection() {
                            return correction;
                        }

                        /**
                         * Sets the value of the correction property.
                         * 
                         */
                        public void setCorrection(boolean value) {
                            this.correction = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="choix" maxOccurs="unbounded" minOccurs="2">
                 *           &lt;complexType>
                 *             &lt;simpleContent>
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
                 *               &lt;/extension>
                 *             &lt;/simpleContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *         &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "choix",
                    "correction"
                })
                public static class ChoixMultiples {

                    @XmlElement(required = true)
                    protected List<Examen.Enonce.Exercice.Question.ChoixMultiples.Choix> choix;
                    @XmlElement(required = true)
                    @XmlSchemaType(name = "positiveInteger")
                    protected BigInteger correction;

                    /**
                     * Gets the value of the choix property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the choix property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getChoix().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Examen.Enonce.Exercice.Question.ChoixMultiples.Choix }
                     * 
                     * 
                     */
                    public List<Examen.Enonce.Exercice.Question.ChoixMultiples.Choix> getChoix() {
                        if (choix == null) {
                            choix = new ArrayList<Examen.Enonce.Exercice.Question.ChoixMultiples.Choix>();
                        }
                        return this.choix;
                    }

                    /**
                     * Gets the value of the correction property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getCorrection() {
                        return correction;
                    }

                    /**
                     * Sets the value of the correction property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setCorrection(BigInteger value) {
                        this.correction = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;simpleContent>
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
                     *     &lt;/extension>
                     *   &lt;/simpleContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Choix {

                        @XmlValue
                        protected String value;
                        @XmlAttribute(required = true)
                        @XmlSchemaType(name = "positiveInteger")
                        protected BigInteger id;

                        /**
                         * Gets the value of the value property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the id property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigInteger }
                         *     
                         */
                        public BigInteger getId() {
                            return id;
                        }

                        /**
                         * Sets the value of the id property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigInteger }
                         *     
                         */
                        public void setId(BigInteger value) {
                            this.id = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="segment" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="typeCorrection">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *                         &lt;enumeration value="syntaxeSeulement"/>
                 *                         &lt;enumeration value="testCompilationPuisExecution"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                   &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
                 *                 &lt;/sequence>
                 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "segment"
                })
                public static class CodeOuTexte {

                    @XmlElement(required = true)
                    protected List<Examen.Enonce.Exercice.Question.CodeOuTexte.Segment> segment;

                    /**
                     * Gets the value of the segment property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the segment property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getSegment().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Examen.Enonce.Exercice.Question.CodeOuTexte.Segment }
                     * 
                     * 
                     */
                    public List<Examen.Enonce.Exercice.Question.CodeOuTexte.Segment> getSegment() {
                        if (segment == null) {
                            segment = new ArrayList<Examen.Enonce.Exercice.Question.CodeOuTexte.Segment>();
                        }
                        return this.segment;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="typeCorrection">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;enumeration value="syntaxeSeulement"/>
                     *               &lt;enumeration value="testCompilationPuisExecution"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *         &lt;element name="correction" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
                     *       &lt;/sequence>
                     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "typeCorrection",
                        "correction"
                    })
                    public static class Segment {

                        @XmlElement(required = true)
                        protected String typeCorrection;
                        @XmlElement(required = true)
                        protected List<String> correction;
                        @XmlAttribute(required = true)
                        protected int id;

                        /**
                         * Gets the value of the typeCorrection property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getTypeCorrection() {
                            return typeCorrection;
                        }

                        /**
                         * Sets the value of the typeCorrection property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setTypeCorrection(String value) {
                            this.typeCorrection = value;
                        }

                        /**
                         * Gets the value of the correction property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the correction property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getCorrection().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link String }
                         * 
                         * 
                         */
                        public List<String> getCorrection() {
                            if (correction == null) {
                                correction = new ArrayList<String>();
                            }
                            return this.correction;
                        }

                        /**
                         * Gets the value of the id property.
                         * 
                         */
                        public int getId() {
                            return id;
                        }

                        /**
                         * Sets the value of the id property.
                         * 
                         */
                        public void setId(int value) {
                            this.id = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="nbEssais" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
                 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="duree" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="nbPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Protocole {

                    @XmlValue
                    protected String value;
                    @XmlAttribute
                    protected String nbEssais;
                    @XmlAttribute
                    protected String version;
                    @XmlAttribute
                    protected String duree;
                    @XmlAttribute(required = true)
                    protected String nbPoints;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the nbEssais property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNbEssais() {
                        if (nbEssais == null) {
                            return "1";
                        } else {
                            return nbEssais;
                        }
                    }

                    /**
                     * Sets the value of the nbEssais property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNbEssais(String value) {
                        this.nbEssais = value;
                    }

                    /**
                     * Gets the value of the version property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getVersion() {
                        return version;
                    }

                    /**
                     * Sets the value of the version property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setVersion(String value) {
                        this.version = value;
                    }

                    /**
                     * Gets the value of the duree property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDuree() {
                        return duree;
                    }

                    /**
                     * Sets the value of the duree property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDuree(String value) {
                        this.duree = value;
                    }

                    /**
                     * Gets the value of the nbPoints property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNbPoints() {
                        return nbPoints;
                    }

                    /**
                     * Sets the value of the nbPoints property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNbPoints(String value) {
                        this.nbPoints = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="enTete">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="objet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="auteur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="destination" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="UV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="coefficient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="commentaires" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enTete",
        "destination",
        "version",
        "commentaires"
    })
    public static class Information {

        @XmlElement(required = true)
        protected Examen.Information.EnTete enTete;
        protected Examen.Information.Destination destination;
        protected String version;
        protected String commentaires;

        /**
         * Gets the value of the enTete property.
         * 
         * @return
         *     possible object is
         *     {@link Examen.Information.EnTete }
         *     
         */
        public Examen.Information.EnTete getEnTete() {
            return enTete;
        }

        /**
         * Sets the value of the enTete property.
         * 
         * @param value
         *     allowed object is
         *     {@link Examen.Information.EnTete }
         *     
         */
        public void setEnTete(Examen.Information.EnTete value) {
            this.enTete = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link Examen.Information.Destination }
         *     
         */
        public Examen.Information.Destination getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link Examen.Information.Destination }
         *     
         */
        public void setDestination(Examen.Information.Destination value) {
            this.destination = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the commentaires property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCommentaires() {
            return commentaires;
        }

        /**
         * Sets the value of the commentaires property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCommentaires(String value) {
            this.commentaires = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="UV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="coefficient" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "uv",
            "module",
            "coefficient"
        })
        public static class Destination {

            @XmlElement(name = "UV")
            protected String uv;
            protected String module;
            protected String coefficient;

            /**
             * Gets the value of the uv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUV() {
                return uv;
            }

            /**
             * Sets the value of the uv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUV(String value) {
                this.uv = value;
            }

            /**
             * Gets the value of the module property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModule() {
                return module;
            }

            /**
             * Sets the value of the module property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModule(String value) {
                this.module = value;
            }

            /**
             * Gets the value of the coefficient property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCoefficient() {
                return coefficient;
            }

            /**
             * Sets the value of the coefficient property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCoefficient(String value) {
                this.coefficient = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="titre" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="objet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="auteur" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="source" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "titre",
            "objet",
            "date",
            "auteur",
            "source"
        })
        public static class EnTete {

            @XmlElement(required = true)
            protected String titre;
            protected String objet;
            protected String date;
            protected String auteur;
            protected String source;

            /**
             * Gets the value of the titre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitre() {
                return titre;
            }

            /**
             * Sets the value of the titre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitre(String value) {
                this.titre = value;
            }

            /**
             * Gets the value of the objet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getObjet() {
                return objet;
            }

            /**
             * Sets the value of the objet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setObjet(String value) {
                this.objet = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the auteur property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuteur() {
                return auteur;
            }

            /**
             * Sets the value of the auteur property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuteur(String value) {
                this.auteur = value;
            }

            /**
             * Gets the value of the source property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSource(String value) {
                this.source = value;
            }

        }

    }

}
