//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.17 at 10:47:10 AM CET 
//


package fr.emn.examination.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.emn.examination.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.emn.examination.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Examen }
     * 
     */
    public Examen createExamen() {
        return new Examen();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.ChoixMultiples }
     * 
     */
    public Examen.Enonce.Exercice.Question.ChoixMultiples createExamenEnonceExerciceQuestionChoixMultiples() {
        return new Examen.Enonce.Exercice.Question.ChoixMultiples();
    }

    /**
     * Create an instance of {@link Examen.Information }
     * 
     */
    public Examen.Information createExamenInformation() {
        return new Examen.Information();
    }

    /**
     * Create an instance of {@link Examen.Information.EnTete }
     * 
     */
    public Examen.Information.EnTete createExamenInformationEnTete() {
        return new Examen.Information.EnTete();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question }
     * 
     */
    public Examen.Enonce.Exercice.Question createExamenEnonceExerciceQuestion() {
        return new Examen.Enonce.Exercice.Question();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.Caseacocher.Case }
     * 
     */
    public Examen.Enonce.Exercice.Question.Caseacocher.Case createExamenEnonceExerciceQuestionCaseacocherCase() {
        return new Examen.Enonce.Exercice.Question.Caseacocher.Case();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.Caseacocher }
     * 
     */
    public Examen.Enonce.Exercice.Question.Caseacocher createExamenEnonceExerciceQuestionCaseacocher() {
        return new Examen.Enonce.Exercice.Question.Caseacocher();
    }

    /**
     * Create an instance of {@link Examen.Enonce }
     * 
     */
    public Examen.Enonce createExamenEnonce() {
        return new Examen.Enonce();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice }
     * 
     */
    public Examen.Enonce.Exercice createExamenEnonceExercice() {
        return new Examen.Enonce.Exercice();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.CodeOuTexte.Segment }
     * 
     */
    public Examen.Enonce.Exercice.Question.CodeOuTexte.Segment createExamenEnonceExerciceQuestionCodeOuTexteSegment() {
        return new Examen.Enonce.Exercice.Question.CodeOuTexte.Segment();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.CodeOuTexte }
     * 
     */
    public Examen.Enonce.Exercice.Question.CodeOuTexte createExamenEnonceExerciceQuestionCodeOuTexte() {
        return new Examen.Enonce.Exercice.Question.CodeOuTexte();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.ChoixMultiples.Choix }
     * 
     */
    public Examen.Enonce.Exercice.Question.ChoixMultiples.Choix createExamenEnonceExerciceQuestionChoixMultiplesChoix() {
        return new Examen.Enonce.Exercice.Question.ChoixMultiples.Choix();
    }

    /**
     * Create an instance of {@link Examen.Information.Destination }
     * 
     */
    public Examen.Information.Destination createExamenInformationDestination() {
        return new Examen.Information.Destination();
    }

    /**
     * Create an instance of {@link Examen.Enonce.Exercice.Question.Protocole }
     * 
     */
    public Examen.Enonce.Exercice.Question.Protocole createExamenEnonceExerciceQuestionProtocole() {
        return new Examen.Enonce.Exercice.Question.Protocole();
    }

}
